package io.github.jseproject;

import org.tritonus.share.sampled.convert.TMatrixFormatConversionProvider;

import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import java.util.Arrays;

public class WavPackFormatConversionProvider extends TMatrixFormatConversionProvider {

    private static final AudioFormat[] INPUT_FORMATS = new AudioFormat[] {
            new AudioFormat(WavPackEncoding.WAVPACK, 6000.0f, -1, 1, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 6000.0f, -1, 2, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 8000.0f, -1, 1, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 8000.0f, -1, 2, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 9600.0f, -1, 1, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 9600.0f, -1, 2, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 11025.0f, -1, 1, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 11025.0f, -1, 2, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 12000.0f, -1, 1, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 12000.0f, -1, 2, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 16000.0f, -1, 1, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 16000.0f, -1, 2, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 22050.0f, -1, 1, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 22050.0f, -1, 2, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 24000.0f, -1, 1, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 24000.0f, -1, 2, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 32000.0f, -1, 1, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 32000.0f, -1, 2, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 44100.0f, -1, 1, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 44100.0f, -1, 2, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 48000.0f, -1, 1, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 48000.0f, -1, 2, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 64000.0f, -1, 1, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 64000.0f, -1, 2, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 88200.0f, -1, 1, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 88200.0f, -1, 2, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 96000.0f, -1, 1, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 96000.0f, -1, 2, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 192000.0f, -1, 1, -1, -1, false),
            new AudioFormat(WavPackEncoding.WAVPACK, 192000.0f, -1, 2, -1, -1, false),
    };

    private static final AudioFormat[] OUTPUT_FORMATS = new AudioFormat[] {
            new AudioFormat(6000.0f, 8, 1, false, false),
            new AudioFormat(6000.0f, 8, 1, false, true),
            new AudioFormat(6000.0f, 8, 2, false, false),
            new AudioFormat(6000.0f, 8, 2, false, true),
            new AudioFormat(6000.0f, 16, 1, true, false),
            new AudioFormat(6000.0f, 16, 1, true, true),
            new AudioFormat(6000.0f, 16, 2, true, false),
            new AudioFormat(6000.0f, 16, 2, true, true),
            new AudioFormat(6000.0f, 24, 1, false, false),
            new AudioFormat(6000.0f, 24, 1, false, true),
            new AudioFormat(6000.0f, 24, 2, false, false),
            new AudioFormat(6000.0f, 24, 2, false, true),
            new AudioFormat(6000.0f, 32, 1, true, false),
            new AudioFormat(6000.0f, 32, 1, true, true),
            new AudioFormat(6000.0f, 32, 2, true, false),
            new AudioFormat(6000.0f, 32, 2, true, true),
            new AudioFormat(8000.0f, 8, 1, false, false),
            new AudioFormat(8000.0f, 8, 1, false, true),
            new AudioFormat(8000.0f, 8, 2, false, false),
            new AudioFormat(8000.0f, 8, 2, false, true),
            new AudioFormat(8000.0f, 16, 1, true, false),
            new AudioFormat(8000.0f, 16, 1, true, true),
            new AudioFormat(8000.0f, 16, 2, true, false),
            new AudioFormat(8000.0f, 16, 2, true, true),
            new AudioFormat(8000.0f, 24, 1, false, false),
            new AudioFormat(8000.0f, 24, 1, false, true),
            new AudioFormat(8000.0f, 24, 2, false, false),
            new AudioFormat(8000.0f, 24, 2, false, true),
            new AudioFormat(8000.0f, 32, 1, true, false),
            new AudioFormat(8000.0f, 32, 1, true, true),
            new AudioFormat(8000.0f, 32, 2, true, false),
            new AudioFormat(8000.0f, 32, 2, true, true),
            new AudioFormat(9600.0f, 8, 1, false, false),
            new AudioFormat(9600.0f, 8, 1, false, true),
            new AudioFormat(9600.0f, 8, 2, false, false),
            new AudioFormat(9600.0f, 8, 2, false, true),
            new AudioFormat(9600.0f, 16, 1, true, false),
            new AudioFormat(9600.0f, 16, 1, true, true),
            new AudioFormat(9600.0f, 16, 2, true, false),
            new AudioFormat(9600.0f, 16, 2, true, true),
            new AudioFormat(9600.0f, 24, 1, false, false),
            new AudioFormat(9600.0f, 24, 1, false, true),
            new AudioFormat(9600.0f, 24, 2, false, false),
            new AudioFormat(9600.0f, 24, 2, false, true),
            new AudioFormat(9600.0f, 32, 1, true, false),
            new AudioFormat(9600.0f, 32, 1, true, true),
            new AudioFormat(9600.0f, 32, 2, true, false),
            new AudioFormat(9600.0f, 32, 2, true, true),
            new AudioFormat(11025.0f, 8, 1, false, false),
            new AudioFormat(11025.0f, 8, 1, false, true),
            new AudioFormat(11025.0f, 8, 2, false, false),
            new AudioFormat(11025.0f, 8, 2, false, true),
            new AudioFormat(11025.0f, 16, 1, true, false),
            new AudioFormat(11025.0f, 16, 1, true, true),
            new AudioFormat(11025.0f, 16, 2, true, false),
            new AudioFormat(11025.0f, 16, 2, true, true),
            new AudioFormat(11025.0f, 24, 1, false, false),
            new AudioFormat(11025.0f, 24, 1, false, true),
            new AudioFormat(11025.0f, 24, 2, false, false),
            new AudioFormat(11025.0f, 24, 2, false, true),
            new AudioFormat(11025.0f, 32, 1, true, false),
            new AudioFormat(11025.0f, 32, 1, true, true),
            new AudioFormat(11025.0f, 32, 2, true, false),
            new AudioFormat(11025.0f, 32, 2, true, true),
            new AudioFormat(12000.0f, 8, 1, false, false),
            new AudioFormat(12000.0f, 8, 1, false, true),
            new AudioFormat(12000.0f, 8, 2, false, false),
            new AudioFormat(12000.0f, 8, 2, false, true),
            new AudioFormat(12000.0f, 16, 1, true, false),
            new AudioFormat(12000.0f, 16, 1, true, true),
            new AudioFormat(12000.0f, 16, 2, true, false),
            new AudioFormat(12000.0f, 16, 2, true, true),
            new AudioFormat(12000.0f, 24, 1, false, false),
            new AudioFormat(12000.0f, 24, 1, false, true),
            new AudioFormat(12000.0f, 24, 2, false, false),
            new AudioFormat(12000.0f, 24, 2, false, true),
            new AudioFormat(12000.0f, 32, 1, true, false),
            new AudioFormat(12000.0f, 32, 1, true, true),
            new AudioFormat(12000.0f, 32, 2, true, false),
            new AudioFormat(12000.0f, 32, 2, true, true),
            new AudioFormat(16000.0f, 8, 1, false, false),
            new AudioFormat(16000.0f, 8, 1, false, true),
            new AudioFormat(16000.0f, 8, 2, false, false),
            new AudioFormat(16000.0f, 8, 2, false, true),
            new AudioFormat(16000.0f, 16, 1, true, false),
            new AudioFormat(16000.0f, 16, 1, true, true),
            new AudioFormat(16000.0f, 16, 2, true, false),
            new AudioFormat(16000.0f, 16, 2, true, true),
            new AudioFormat(16000.0f, 24, 1, false, false),
            new AudioFormat(16000.0f, 24, 1, false, true),
            new AudioFormat(16000.0f, 24, 2, false, false),
            new AudioFormat(16000.0f, 24, 2, false, true),
            new AudioFormat(16000.0f, 32, 1, true, false),
            new AudioFormat(16000.0f, 32, 1, true, true),
            new AudioFormat(16000.0f, 32, 2, true, false),
            new AudioFormat(16000.0f, 32, 2, true, true),
            new AudioFormat(22050.0f, 8, 1, false, false),
            new AudioFormat(22050.0f, 8, 1, false, true),
            new AudioFormat(22050.0f, 8, 2, false, false),
            new AudioFormat(22050.0f, 8, 2, false, true),
            new AudioFormat(22050.0f, 16, 1, true, false),
            new AudioFormat(22050.0f, 16, 1, true, true),
            new AudioFormat(22050.0f, 16, 2, true, false),
            new AudioFormat(22050.0f, 16, 2, true, true),
            new AudioFormat(22050.0f, 24, 1, false, false),
            new AudioFormat(22050.0f, 24, 1, false, true),
            new AudioFormat(22050.0f, 24, 2, false, false),
            new AudioFormat(22050.0f, 24, 2, false, true),
            new AudioFormat(22050.0f, 32, 1, true, false),
            new AudioFormat(22050.0f, 32, 1, true, true),
            new AudioFormat(22050.0f, 32, 2, true, false),
            new AudioFormat(22050.0f, 32, 2, true, true),
            new AudioFormat(24000.0f, 8, 1, false, false),
            new AudioFormat(24000.0f, 8, 1, false, true),
            new AudioFormat(24000.0f, 8, 2, false, false),
            new AudioFormat(24000.0f, 8, 2, false, true),
            new AudioFormat(24000.0f, 16, 1, true, false),
            new AudioFormat(24000.0f, 16, 1, true, true),
            new AudioFormat(24000.0f, 16, 2, true, false),
            new AudioFormat(24000.0f, 16, 2, true, true),
            new AudioFormat(24000.0f, 24, 1, false, false),
            new AudioFormat(24000.0f, 24, 1, false, true),
            new AudioFormat(24000.0f, 24, 2, false, false),
            new AudioFormat(24000.0f, 24, 2, false, true),
            new AudioFormat(24000.0f, 32, 1, true, false),
            new AudioFormat(24000.0f, 32, 1, true, true),
            new AudioFormat(24000.0f, 32, 2, true, false),
            new AudioFormat(24000.0f, 32, 2, true, true),
            new AudioFormat(32000.0f, 8, 1, false, false),
            new AudioFormat(32000.0f, 8, 1, false, true),
            new AudioFormat(32000.0f, 8, 2, false, false),
            new AudioFormat(32000.0f, 8, 2, false, true),
            new AudioFormat(32000.0f, 16, 1, true, false),
            new AudioFormat(32000.0f, 16, 1, true, true),
            new AudioFormat(32000.0f, 16, 2, true, false),
            new AudioFormat(32000.0f, 16, 2, true, true),
            new AudioFormat(32000.0f, 24, 1, false, false),
            new AudioFormat(32000.0f, 24, 1, false, true),
            new AudioFormat(32000.0f, 24, 2, false, false),
            new AudioFormat(32000.0f, 24, 2, false, true),
            new AudioFormat(32000.0f, 32, 1, true, false),
            new AudioFormat(32000.0f, 32, 1, true, true),
            new AudioFormat(32000.0f, 32, 2, true, false),
            new AudioFormat(32000.0f, 32, 2, true, true),
            new AudioFormat(44100.0f, 8, 1, false, false),
            new AudioFormat(44100.0f, 8, 1, false, true),
            new AudioFormat(44100.0f, 8, 2, false, false),
            new AudioFormat(44100.0f, 8, 2, false, true),
            new AudioFormat(44100.0f, 16, 1, true, false),
            new AudioFormat(44100.0f, 16, 1, true, true),
            new AudioFormat(44100.0f, 16, 2, true, false),
            new AudioFormat(44100.0f, 16, 2, true, true),
            new AudioFormat(44100.0f, 24, 1, false, false),
            new AudioFormat(44100.0f, 24, 1, false, true),
            new AudioFormat(44100.0f, 24, 2, false, false),
            new AudioFormat(44100.0f, 24, 2, false, true),
            new AudioFormat(44100.0f, 32, 1, true, false),
            new AudioFormat(44100.0f, 32, 1, true, true),
            new AudioFormat(44100.0f, 32, 2, true, false),
            new AudioFormat(44100.0f, 32, 2, true, true),
            new AudioFormat(48000.0f, 8, 1, false, false),
            new AudioFormat(48000.0f, 8, 1, false, true),
            new AudioFormat(48000.0f, 8, 2, false, false),
            new AudioFormat(48000.0f, 8, 2, false, true),
            new AudioFormat(48000.0f, 16, 1, true, false),
            new AudioFormat(48000.0f, 16, 1, true, true),
            new AudioFormat(48000.0f, 16, 2, true, false),
            new AudioFormat(48000.0f, 16, 2, true, true),
            new AudioFormat(48000.0f, 24, 1, false, false),
            new AudioFormat(48000.0f, 24, 1, false, true),
            new AudioFormat(48000.0f, 24, 2, false, false),
            new AudioFormat(48000.0f, 24, 2, false, true),
            new AudioFormat(48000.0f, 32, 1, true, false),
            new AudioFormat(48000.0f, 32, 1, true, true),
            new AudioFormat(48000.0f, 32, 2, true, false),
            new AudioFormat(48000.0f, 32, 2, true, true),
            new AudioFormat(64000.0f, 8, 1, false, false),
            new AudioFormat(64000.0f, 8, 1, false, true),
            new AudioFormat(64000.0f, 8, 2, false, false),
            new AudioFormat(64000.0f, 8, 2, false, true),
            new AudioFormat(64000.0f, 16, 1, true, false),
            new AudioFormat(64000.0f, 16, 1, true, true),
            new AudioFormat(64000.0f, 16, 2, true, false),
            new AudioFormat(64000.0f, 16, 2, true, true),
            new AudioFormat(64000.0f, 24, 1, false, false),
            new AudioFormat(64000.0f, 24, 1, false, true),
            new AudioFormat(64000.0f, 24, 2, false, false),
            new AudioFormat(64000.0f, 24, 2, false, true),
            new AudioFormat(64000.0f, 32, 1, true, false),
            new AudioFormat(64000.0f, 32, 1, true, true),
            new AudioFormat(64000.0f, 32, 2, true, false),
            new AudioFormat(64000.0f, 32, 2, true, true),
            new AudioFormat(82000.0f, 8, 1, false, false),
            new AudioFormat(82000.0f, 8, 1, false, true),
            new AudioFormat(82000.0f, 8, 2, false, false),
            new AudioFormat(82000.0f, 8, 2, false, true),
            new AudioFormat(82000.0f, 16, 1, true, false),
            new AudioFormat(82000.0f, 16, 1, true, true),
            new AudioFormat(82000.0f, 16, 2, true, false),
            new AudioFormat(82000.0f, 16, 2, true, true),
            new AudioFormat(82000.0f, 24, 1, false, false),
            new AudioFormat(82000.0f, 24, 1, false, true),
            new AudioFormat(82000.0f, 24, 2, false, false),
            new AudioFormat(82000.0f, 24, 2, false, true),
            new AudioFormat(82000.0f, 32, 1, true, false),
            new AudioFormat(82000.0f, 32, 1, true, true),
            new AudioFormat(82000.0f, 32, 2, true, false),
            new AudioFormat(82000.0f, 32, 2, true, true),
            new AudioFormat(96000.0f, 8, 1, false, false),
            new AudioFormat(96000.0f, 8, 1, false, true),
            new AudioFormat(96000.0f, 8, 2, false, false),
            new AudioFormat(96000.0f, 8, 2, false, true),
            new AudioFormat(96000.0f, 16, 1, true, false),
            new AudioFormat(96000.0f, 16, 1, true, true),
            new AudioFormat(96000.0f, 16, 2, true, false),
            new AudioFormat(96000.0f, 16, 2, true, true),
            new AudioFormat(96000.0f, 24, 1, false, false),
            new AudioFormat(96000.0f, 24, 1, false, true),
            new AudioFormat(96000.0f, 24, 2, false, false),
            new AudioFormat(96000.0f, 24, 2, false, true),
            new AudioFormat(96000.0f, 32, 1, true, false),
            new AudioFormat(96000.0f, 32, 1, true, true),
            new AudioFormat(96000.0f, 32, 2, true, false),
            new AudioFormat(96000.0f, 32, 2, true, true),
            new AudioFormat(192000.0f, 8, 1, false, false),
            new AudioFormat(192000.0f, 8, 1, false, true),
            new AudioFormat(192000.0f, 8, 2, false, false),
            new AudioFormat(192000.0f, 8, 2, false, true),
            new AudioFormat(192000.0f, 16, 1, true, false),
            new AudioFormat(192000.0f, 16, 1, true, true),
            new AudioFormat(192000.0f, 16, 2, true, false),
            new AudioFormat(192000.0f, 16, 2, true, true),
            new AudioFormat(192000.0f, 24, 1, false, false),
            new AudioFormat(192000.0f, 24, 1, false, true),
            new AudioFormat(192000.0f, 24, 2, false, false),
            new AudioFormat(192000.0f, 24, 2, false, true),
            new AudioFormat(192000.0f, 32, 1, true, false),
            new AudioFormat(192000.0f, 32, 1, true, true),
            new AudioFormat(192000.0f, 32, 2, true, false),
            new AudioFormat(192000.0f, 32, 2, true, true),
    };

    private static final boolean t = true;
    private static final boolean f = false;

    private static final boolean[][] CONVERSIONS = new boolean[][] {
            new boolean[] {t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t},
            new boolean[] {f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,
                    f,f,f,f,f,f,f,f,f,f,f,f,f,f,f,f, t,t,t,t,t,t,t,t,t,t,t,t,t,t,t,t},
    };

    public WavPackFormatConversionProvider() {
        super(Arrays.asList(INPUT_FORMATS), Arrays.asList(OUTPUT_FORMATS), CONVERSIONS);
    }

    @Override
    public AudioInputStream getAudioInputStream(AudioFormat targetFormat, AudioInputStream audioInputStream) {
        if (audioInputStream instanceof WavPackAudioInputStream && isConversionSupported(targetFormat, audioInputStream.getFormat()))
            return new DecodedWavPackAudioInputStream(targetFormat, (WavPackAudioInputStream) audioInputStream);
        else throw new IllegalArgumentException("conversion not supported");
    }

}
